//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class EditableInformesSetGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditableInformesSetGrid() : base("LightSwitchApplication.TESThtml8.DesktopClient:EditableInformesSetGrid")
        {
            global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditableInformesSetGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditableInformesSetGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableInformesSetGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void InformesSet_SelectionChanged();

        partial void InformesSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InformesSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the InformesSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Informes> InformesSet
        {
            get
            {
                return global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties.InformesSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InformesSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the enviarMissatge screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void enviarMissatge()
        {
            this.Details.Methods.enviarMissatge.CreateInvocation().Execute();
        }
        partial void enviarMissatge_CanExecute(ref bool result);
        partial void enviarMissatge_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties.InformesSet;
                var initializeCommandEntry = global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSetProperties.enviarMissatge;
                var initializeMethodEntry = global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSetProperties.enviarMissatge;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry
                __EditableInformesSetGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeCreated,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeActivated,
                    global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.__EditableInformesSetGrid_InvokeSaveErrorEvent);
            private static void __EditableInformesSetGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditableInformesSetGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditableInformesSetGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditableInformesSetGrid_InvokeSavingEvent(global::LightSwitchApplication.EditableInformesSetGrid s)
            {
                bool handled = false;
                s.EditableInformesSetGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditableInformesSetGrid_InvokeSavedEvent(global::LightSwitchApplication.EditableInformesSetGrid s)
            {
                s.EditableInformesSetGrid_Saved();
            }
            private static bool __EditableInformesSetGrid_InvokeClosingEvent(global::LightSwitchApplication.EditableInformesSetGrid s)
            {
                bool cancel = false;
                s.EditableInformesSetGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditableInformesSetGrid_InvokeCreated(global::LightSwitchApplication.EditableInformesSetGrid s)
            {
                s.EditableInformesSetGrid_Created();
            }
            private static void __EditableInformesSetGrid_InvokeActivated(global::LightSwitchApplication.EditableInformesSetGrid s)
            {
                s.EditableInformesSetGrid_Activated();
            }
            private static bool __EditableInformesSetGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditableInformesSetGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditableInformesSetGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable InformesSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.InformesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes>.Data _InformesSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Data _enviarMissatgeCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Data _enviarMissatgeMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes> InformesSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes>)base.GetItem(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties.InformesSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass> enviarMissatge
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>)base.GetItem(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSetProperties.enviarMissatge);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass> enviarMissatge
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>)base.GetItem(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSetProperties.enviarMissatge);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes>.Entry
                    InformesSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes>.Entry(
                        "InformesSet",
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_Stub,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_Validate,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_CreateQuery,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_SelectionChanged,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_OnCollectionChanged,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.PropertySetProperties._InformesSet_OnLoaded);
                private static void _InformesSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::LightSwitchApplication.Informes>.Data> c, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._InformesSet, sf);
                }
                private static void _InformesSet_Validate(global::LightSwitchApplication.EditableInformesSetGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.InformesSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _InformesSet_CreateQuery(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, object[] args)
                {
                    return d.InformesSetQuery();
                }
                private static void _InformesSet_SelectionChanged(global::LightSwitchApplication.EditableInformesSetGrid s)
                {
                    s.InformesSet_SelectionChanged();
                }
                private static void _InformesSet_OnCollectionChanged(global::LightSwitchApplication.EditableInformesSetGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.InformesSet_Changed(e);
                }
                private static void _InformesSet_OnLoaded(global::LightSwitchApplication.EditableInformesSetGrid s, bool succeeded)
                {
                    s.InformesSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry
                    enviarMissatge = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry(
                        "enviarMissatge",
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSetProperties._enviarMissatge_Stub,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.CommandSetProperties._enviarMissatge_CreateExecutableObject);
                private static void _enviarMissatge_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Data> c, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._enviarMissatgeCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _enviarMissatge_CreateExecutableObject(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass)d).Methods.enviarMissatge.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry
                    enviarMissatge = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Entry(
                        "enviarMissatge",
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSetProperties._enviarMissatge_Stub,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSetProperties._enviarMissatge_CanInvoke,
                        global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass.MethodSetProperties._enviarMissatge_InvokeMethod);
                private static void _enviarMissatge_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.EditableInformesSetGrid, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass>.Data> c, global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._enviarMissatgeMethod, sf);
                }
                private static global::System.Exception _enviarMissatge_CanInvoke(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.enviarMissatge_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _enviarMissatge_InvokeMethod(global::LightSwitchApplication.EditableInformesSetGrid.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.enviarMissatge_Execute();
                }

            }
        }
    }
}
